# Generated by Django 4.0.2 on 2022-02-09 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('sales', '0001_initial'), ('sales', '0002_rename_users_item_buyers'), ('sales', '0003_alter_store_id_alter_store_name'), ('sales', '0004_alter_buyer_username_alter_item_name_alter_store_id_and_more'), ('sales', '0005_owner_alter_store_owner')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='user')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='store')),
                ('owner', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='item', max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=60)),
                ('image', models.URLField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.store')),
                ('buyers', models.ManyToManyField(to='sales.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='owner')),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.owner'),
        ),
    ]
