# Generated by Django 4.0.2 on 2022-02-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_squashed_0005_owner_alter_store_owner'),
    ]

    operations = [
    ]
