# Generated by Django 4.0.2 on 2022-02-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_store_description_alter_buyer_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='buyers',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Purchased')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.buyer')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.item')),
            ],
        ),
    ]
